### PR TITLE
Make resourceTypeID of trigger an array to allow multiple resource types

### LINKED ISSUE #135: Triggers is a block instead of array in tf
For resource "commercetools_api_extension" it currently isn't possible to create a trigger for multiple resource_type_ids, which technically is possible through the commerceTools API.
 
It isn't a blocker since we can create multiple api_entension resources (1 per trigger)

commercetools api extension doc:
triggers - Array of Trigger - Describes what triggers the extension

### PR DESCRIPTION
**Pull request by qdegraaf**
Resolves #135

### CODE REVIEW

**Comment by mvantellingen** [comment]
Is this backwards compatible? (do we still accept a literal?)

**Comment by qdegraaf** [comment]
No this will not be compatible. The provider will throw a type error like:
`Incorrect attribute value type: Inappropriate value for attribute "resource_type_id": list of string required.`
if you try and pass in a string literal. Unsure whether there is an easy workaround to allow for both `schema.TypeString` and `schema.TypeList` to be possible, and whether we would want that if it exists.

**Comment by mvantellingen** [comment]
I'm really not sure about this. I'm pretty happy with the following syntax (which is as implemented currently, although with some issues)

```hcl
  trigger {
    resource_type_id = "order"
    actions          = ["Create"]
  }

  trigger {
    resource_type_id = "cart"
    actions          = ["Create", "Update"]
  }

  trigger {
    resource_type_id = "payment"
    actions          = ["Create"]
  }
```

**Comment by qdegraaf** [comment]
Agreed with @mvantellingen that multiple blocks is probably the best way to implement this if #129 is fixed. Will do that and close this for now

**Pull request closed without merging**
