### PR TITLE
feat(business-unit): add business unit tf resource

### PR DESCRIPTION
**Pull request by VictorAvelar**
## Description

Adds business units as a plugin resource.

### NEW FEATURES | UPGRADE NOTES | ENHANCEMENTS | BUG FIXES | EXPERIMENTS

 

-  Enables the provider to manage BusinessUnit resources.

✅  Depends on: https://github.com/labd/commercetools-node-mock/pull/109 MERGED

### CODE REVIEW

**Review by demeyerthom — APPROVED** [review]
LGTM

**Comment by demeyerthom** [comment]
@VictorAvelar I had to revert this because I ran into several issues with the data model; i merged it too quickly :)

- TopLevelUnit is a required field, but this is not the case in the drafts. I think it is something that gets computed once child divisions are added. So this feels like something that should not be part of the terraform data model at all, as I don't know if it would be something we need to know about when configuring
- BusinessUnit.ParentUnit is not required, as the top level Company does not have a parent unit
-  business_unit.NewResource was missing in `provider.Provider`, so the resource was never loaded
- For the blocks i would go with singular, so `associate` instead of `associates`

I feel like we would be better of introducing two different resource types for this: `Company` and `Division`. They seem to have similar data models, but behave a bit differently with regards to which data is required and which is not. I am not sure what the future development path is for this feature, so a split could potentially allow us to treat them differently going forward (or shoot ourselves in the foot if not)

What are your thoughts on this?

**Comment by VictorAvelar** [comment]
Hey @demeyerthom, thanks for providing the details. I must say, this one was a bit challenging right from the start. The BusinessUnit is essentially a union type encompassing both Company and Division, with approximately 95% of their information overlapping.

To address your points above:

- Although TopLevelUnit is marked as required in the BusinessUnit type, it isn't mandatory for any of the drafts. This was actually a misunderstanding on my part.
- ParentUnit, on the other hand, is not obligatory for Company but is a requirement for Division, as indicated in the [commercetools docs](https://docs.commercetools.com/api/projects/business-units#divisiondraft).
- I'll definitely take your suggestion regarding naming the resources in the singular form – it makes a lot of sense! 💯

I can recognize the advantages of introducing separate resources, although it might entail an additional step in the learning curve for managing BusinessUnits with terraform. However, I don't believe it would be too steep of a learning curve to navigate so I would like to defer that decision to you as maintainer of the library.

**Comment by demeyerthom** [comment]
Yeah, it is the required on one vs not required on the other that trips me up a bit. I think it will make the code unclear, as most stuff should then not be required, but actually is based on the type. I think we can soften the learning curve by adding a bit more info in the docs themselves

So hereby I make the call to split them to **2 resources,** Company and Division. We can probably get away with having some inheritance in our code so we can treat the same fields uniformly, and then add the additional fields + requirements where necessary.

Would you be ok with looking into this? We currently don't have a business need to implement this yet, so I would probably only come back to this once that need comes up, but I am happy to review

Thanks!

**Comment by VictorAvelar** [comment]
Yeah I'll dive into it, no worries. Thanks for the feedback. 🚀

**Pull request merged**
