### PR TITLE
Added support for custom fields in Cart Discount

### PR DESCRIPTION
**Pull request by bulat-khusnimardanov**
### ENHANCEMENT

- Added custom fields support to the `commercetools_cart_discount` resources.
- Updated documentation.

### CODE REVIEW

**Review by demeyerthom — COMMENTED** [review]
Hi @bulat-khusnimardanov 

This looks good to me. Could you also add some tests to make sure this works?

**Comment by bulat-khusnimardanov** [comment]
> Hi @bulat-khusnimardanov
> 
> This looks good to me. Could you also add some tests to make sure this works?

Hi @demeyerthom,

I tried to do so, but the mock server utilized for the tests does not support this functionality. An example can be found here: [link](https://github.com/bulat-khusnimardanov/terraform-provider-commercetools/actions/runs/5868372418/job/15911049946).
When I executed the same action against the actual commercetools environment, it worked fine.

**Comment by demeyerthom** [comment]
@bulat-khusnimardanov 

Ah we are missing the field in the mock server also. I will see if I can add it and come back to you!

**Comment by demeyerthom** [comment]
@bulat-khusnimardanov alternatively if you have the time you can add it here; https://github.com/labd/commercetools-node-mock/blob/main/src/repositories/cart-discount.ts.

You probably need to add it both in the create method and as one of the actions

**Comment by bulat-khusnimardanov** [comment]
> @bulat-khusnimardanov alternatively if you have the time you can add it here; https://github.com/labd/commercetools-node-mock/blob/main/src/repositories/cart-discount.ts.
> 
> You probably need to add it both in the create method and as one of the actions

I'll have a look.

**Pull request merged**
