### PR TITLE
add GoogleCloudFunction type to resource_api_extension

### PR DESCRIPTION
**Pull request by elvinristi**
Implement new feature - add new type `GoogleCloudFunction`:
- https://github.com/labd/terraform-provider-commercetools/issues/348
- which is also in SDK: https://github.com/labd/commercetools-go-sdk/blob/2a3c3778415c7794f4ea84a449759da4406f450d/platform/types_extension.go#L88-L93

which was announced in 2023-02-17
- https://docs.commercetools.com/api/releases/2023-02-17-introducing-google-cloud-function-destination-for-api-extensions

### CODE REVIEW

**Comment by elvinristi** [comment]
Test result for this code
- https://github.com/vaimo/terraform-provider-commercetools/actions/runs/4322097390/jobs/7544096963

**Comment by elvinristi** [comment]
Hello @mvantellingen,

what you think of this PR? Not a `go` developer but if something needs to be improved to speed up the improvement then welcome to add comments.

Thank you!

**Comment by demeyerthom** [comment]
@elvinristi thanks for contributing!

The changes look good to me! Would you mind adding a bit of documentation in the examples?

You can do this by editing the `examples/resources/commercetools_api_extension/resource.tf` file and adding an example of the terraform resource for the `googlecloudfunction` version there.



After this you can run `go generate ./...` to see the results in docs/resources/api_extension.md which you can commit here also.

**Comment by elvinristi** [comment]
Hello @demeyerthom ! 

Thank you for the merge.

I've tried to update `resource.tf` with following diff, but `go generate ./...` did strange things under "docs/"

```diff
$ git diff examples/resources/commercetools_api_extension/resource.tf
diff --git a/examples/resources/commercetools_api_extension/resource.tf b/examples/resources/commercetools_api_extension/resource.tf
index f3d1d57..5e55186 100644
--- a/examples/resources/commercetools_api_extension/resource.tf
+++ b/examples/resources/commercetools_api_extension/resource.tf
@@ -12,3 +12,38 @@ resource "commercetools_api_extension" "my-extension" {
     actions          = ["Create", "Update"]
   }
 }
+
+# @see https://docs.commercetools.com/api/projects/api-extensions#googlecloudfunctiondestination
+resource "commercetools_api_extension" "my_gcf_extension" {
+  key = "my-extension-key"
+
+  destination {
+    type = "GoogleCloudFunction"
+    url  = "https://example.com"
+  }
+
+  trigger {
+    resource_type_id = "order"
+    actions          = ["Create"]
+  }
+}
+
+resource "google_cloudfunctions_function" "my_cloud_function" {
+  # TODO @see https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudfunctions_function
+}
+
+# For GoogleCloudFunction destinations, you need to grant permissions
+# to the <extensions@commercetools-platform.iam.gserviceaccount.com> service account
+# to invoke your function.
+resource "google_cloudfunctions_function_iam_member" "invoker" {
+  project = "my-project"
+  # TODO assign correct region
+  region         = "europe-central2"
+  cloud_function = google_cloudfunctions_function.my_cloud_function.name
+
+  # If your function's version is 1st gen, grant the service account the IAM role Cloud Functions Invoker
+  role = "roles/cloudfunctions.invoker"
+  # For version 2nd gen, assign the IAM role Cloud Run Invoker
+  # role   = "roles/run.invoker"
+  member = "serviceAccount:extensions@commercetools-platform.iam.gserviceaccount.com"
+}
```



I see that in `release/v1.8.0` there is already something added on this. I think maybe this `google_cloudfunctions_function_iam_member` should be also mentioned there as this important part of that to use `GoogleCloudFunction` type.

**Comment by demeyerthom** [comment]
Hi @elvinristi addition looks good to me! I will update the release branch with your suggested changes!

**Comment by elvinristi** [comment]
Great! Thank you! :)

**Pull request merged**
