### PR TITLE
Adding support for predicate for Shipping Methods

### PR DESCRIPTION
**Pull request by vparikh-express**

### CODE REVIEW

**Comment by vparikh-express** [comment]
What is labd.terraform-provider-commercetools (Test ubuntu) check? It is failing and logs do not have much info.

**Comment by mvantellingen** [comment]
I think the issue is indeed that we need to update the mock server to support the shipping methods. That is done in https://github.com//labd/commercetools-python-sdk 

I might be able to look at it early next week

**Comment by vparikh-express** [comment]
Thanks.

**Comment by mvantellingen** [comment]
I've updated the mock server to support the setPredicate action, squashed your commits (excluding the last one, which worked around the missing functionality) and committed it.

Seems to work! 👍

**Comment by vparikh-express** [comment]
Thank you.

**Pull request closed without merging**
