### PR TITLE
Add descriptions to resources and their fields

### PR DESCRIPTION
**Pull request by qdegraaf**
Adds description strings to all resources and fields to allow `tfplugindocs` to autogenerate documentation for the provider.

Closes https://github.com/labd/terraform-provider-commercetools/issues/156

**Pre merge checklist:**

- [x] Confirm we want to keep old docs until tfplugindocs is in a stable state
- [x] Is there a way to overwrite bits of the template? (e.g. the specific examples of the `api_extension` resource)
- [x] Generate docs

### CODE REVIEW

**Comment by pimvernooij** [comment]
Question: is most of this documentation directly copied from the CT docs? Or is this manually created by us / specific to the terraform provider?

I was wondering whether we could (partly) generate the documentation strings in this file through the generated Go SDK? As the YAML underneath that contains documentation as well, if I recall correctly.

**Comment by tleguijt** [comment]
@qdegraaf examples that are places in the examples directory are automatically included in the docs.
You can further alter the template itself. More info: https://github.com/hashicorp/terraform-plugin-docs#conventional-paths

But for now, and for the scope of this PR; let's just focus on the descriptions

**Comment by qdegraaf** [comment]
> Question: is most of this documentation directly copied from the CT docs? Or is this manually created by us / specific to the terraform provider?
> 
> I was wondering whether we could (partly) generate the documentation strings in this file through the generated Go SDK? As the YAML underneath that contains documentation as well, if I recall correctly.

With minor edits, most of this is from the CT docs. We could definitely look into auto generating (parts) of it 



> @qdegraaf examples that are places in the examples directory are automatically included in the docs.
> You can further alter the template itself. More info: https://github.com/hashicorp/terraform-plugin-docs#conventional-paths
> 
> But for now, and for the scope of this PR; let's just focus on the descriptions

Thanks for the info. Agreed that it's out of scope for this PR though we should do a check that all additional information that is in the old style docs, is present in some form in the new style docs, before we make the jump and remove the old docs.

**Comment by tleguijt** [comment]
LGTM!

**Pull request merged**
