### PR TITLE
feat: added cart discount and discount code entities

### PR DESCRIPTION
**Pull request by Autushonak**
### Cart Discount https://docs.commercetools.com/http-api-projects-cartDiscounts

- Added supporting of new commercetools entity CartDiscount
- MultiBuyLineItems Target MultiBuyCustomLineItems Target (https://docs.commercetools.com/http-api-projects-cartDiscounts#multibuylineitems-target) was skipped because in commercetools it is beta feature
- Custom fields skipped 

###  Discount Code https://docs.commercetools.com/http-api-projects-discountCodes

- Custom fields skipped 

In future it is possible to extend this entities with missing fields

Notes:

- local testing was successfull (entities update/createation succcessful)

### CODE REVIEW

**Comment by davidweterings** [comment]
Great work, the code looks good! 

I was about to suggest to add some basic tests :)....

The integration tests use the mock Commercetools server from https://github.com/labd/commercetools-python-sdk which has support for most CartDiscount and DiscountCode operations, f.e. for CartDiscount https://github.com/labd/commercetools-python-sdk/blob/master/src/commercetools/testing/cart_discounts.py#L41 at the bottom you see the actions that are implemented in this mocking backend. 

Let me know if you have any further questions!

**Comment by Autushonak** [comment]
@davidweterings I've updated PR. Could you please review again?

**Comment by Autushonak** [comment]
Hi again!

Could you please review it again? I have covered with basic tests and added documentation https://github.com/labd/terraform-provider-commercetools/pull/114 <https://github.com/labd/terraform-provider-commercetools/pull/114>

Thanks,
Aliaksei

**Comment by andrei-selilo** [comment]
Hi, really interested in this MR.
What are the blockers to merge it?

**Comment by mvantellingen** [comment]
One of the items we still might need to do (and why it wasn't merged yet before) is that the tests run against the commercetools-mock-server and that needs to be updated

**Pull request merged**
